### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aurelia-wdag#1]
Here is my todo list

General:
- [ ] make into plugin
- [ ] define remote datasources
- [ ] define local datasource
- [x] multible datasource from 1 class
- [x] local configuration.json, not calling server for catalog
- [x] connector aurelia-v-grid (modified version)

Datasource:
- [x] query(querystring, options)
- [x] orderby(orderString, options)
- [x] save all()
- [x] save current()
- [ ] refreshCurrent()
- [x] getElement(row)
- [x] select(row)
- [x] call entity methods with get and post
- [x] call entity methods with get and post
- [x] call entity methods with get and post

Entity:
- [x] know when its new
- [x] know when its edited, and set back to original value
- [x] support related with binding to parent
- [x] support related with un-binding to parent
- [x] support long attribute
- [x] support long64 attribute
- [x] support number attribute
- [x] support word attribute
- [x] support byte attribute
- [x] support bool attribute
- [x] support date attribute
- [ ] support image attribute
- [x] support uuid attribute
- [x] support string attribute
- [ ] support object attribute
- [x] support blob attribute
- [ ] support duration attribute
- [ ] undo options...

etc  etc, have a lot thats done, but need a lot more testing

Please make a new issue if you have suggestions, and Ill add them with a link to the issue
